version: '2.0'

services:
  notebook:
    image: at-docker.ad.bcm.edu:5000/pipeline:latest 
    ports:
      - "8887:8888"
      - "8502:8501"
    volumes:
      - /mnt/:/mnt/
      - /home/pipeline_data/:/tmp/
      - .:/data/pipeline/
    env_file: .env
    environment:
      - DISPLAY=$DISPLAY
    entrypoint: /data/pipeline/entrypoint.sh
    working_dir: /


  minion:
    image: ninai/stimulus-pipeline:latest
    volumes:
      - /mnt/:/mnt/
      - /home/pipeline_data:/tmp/
      - .:/data/pipeline
    env_file: .env
    entrypoint:
      - python3 
      - /data/pipeline/python/scripts/populate-minion.py


  minion-gpu:
    image: ninai/pipeline:tf-gpu
    runtime: nvidia
    volumes:
      - /mnt/:/mnt/
      - /home/pipeline_data:/tmp/
      - .:/data/pipeline
    env_file: .env
    entrypoint:
      - python3 
      - /data/pipeline/python/scripts/populate-minion_gpu.py

  
  bash:
    image: ninai/stimulus-pipeline:latest
    volumes:
      - /mnt/:/mnt/
      - /home/pipeline_data/:/tmp/
      - .:/data/pipeline
      - /etc/localtime:/etc/localtime:ro
      - /tmp/.X11-unix:/tmp/.X11-unix
    env_file: .env
    environment:
      - DISPLAY=$DISPLAY
    entrypoint:
      - /bin/bash
